// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TendaUltramarinos.Api.Datos;

#nullable disable

namespace TendaUltramarinos.Api.Migrations
{
    [DbContext(typeof(UltramarinosDbContext))]
    [Migration("20220506214403_Milloras")]
    partial class Milloras
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TendaUltramarinos.Api.Entidades.Cesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cestas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("TendaUltramarinos.Api.Entidades.CestaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cantidade")
                        .HasColumnType("int");

                    b.Property<int>("CestaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CestaItems");
                });

            modelBuilder.Entity("TendaUltramarinos.Api.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cantidade")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImaxeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidade = 100,
                            CategoriaId = 1,
                            Descripcion = "Un kit fabricado por Glossier, que conten productos para o coidado da pel, do pelo e maquillaxe",
                            ImaxeUrl = "/Imaxes/Beleza/Beleza1.png",
                            Nome = "Glossier - Kit de Beleza",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 2,
                            Cantidade = 45,
                            CategoriaId = 1,
                            Descripcion = "Un kit de Curology, que inclue productos para coidar a tua pel",
                            ImaxeUrl = "/Imaxes/Beleza/Beleza2.png",
                            Nome = "Curology - Kit Coidado da Pel",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 3,
                            Cantidade = 30,
                            CategoriaId = 1,
                            Descripcion = "Un kit de Curology, que conten productos para o coidado da pel",
                            ImaxeUrl = "/Imaxes/Beleza/Beleza3.png",
                            Nome = "Cocooil - Aceite de Coco Organico",
                            Precio = 20m
                        },
                        new
                        {
                            Id = 4,
                            Cantidade = 60,
                            CategoriaId = 1,
                            Descripcion = "Un conxunto de productos de Schwarzkopf, que conten productos para o coidado da pel e do pelo",
                            ImaxeUrl = "/Imaxes/Beleza/Beleza4.png",
                            Nome = "Schwarzkopf - Kit de coidado do pelo e da pel",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 5,
                            Cantidade = 85,
                            CategoriaId = 1,
                            Descripcion = "Outro dos kits para coidar a tua pel e o teu pelo, a beleza e o mais importante.",
                            ImaxeUrl = "/Imaxes/Beleza/Beleza5.png",
                            Nome = "Kit Coida Peles",
                            Precio = 30m
                        },
                        new
                        {
                            Id = 6,
                            Cantidade = 120,
                            CategoriaId = 3,
                            Descripcion = "Air Pods - auriculares de tapón sen cables ao alcance do oído, e da tua carteira",
                            ImaxeUrl = "/Imaxes/Electronica/Electronica1.png",
                            Nome = "Air Pods",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 7,
                            Cantidade = 200,
                            CategoriaId = 3,
                            Descripcion = "Auriculares Golden ao alcance do oído - estes auriculares non son wireless",
                            ImaxeUrl = "/Imaxes/Electronica/Electronica2.png",
                            Nome = "Auriculares Golden ao alcance do oído",
                            Precio = 40m
                        },
                        new
                        {
                            Id = 8,
                            Cantidade = 300,
                            CategoriaId = 3,
                            Descripcion = "Auriculares Black - non son wireless",
                            ImaxeUrl = "/Imaxes/Electronica/Electronica3.png",
                            Nome = "Auriculares de Diadema Black",
                            Precio = 40m
                        },
                        new
                        {
                            Id = 9,
                            Cantidade = 20,
                            CategoriaId = 3,
                            Descripcion = "Sennheiser Digital Camera - Camara dixital de alta calidade fabricada por Sennheiser - inclue tripode",
                            ImaxeUrl = "/Imaxes/Electronica/Electronica4.png",
                            Nome = "Sennheiser Digital Camera con Tripode",
                            Precio = 600m
                        },
                        new
                        {
                            Id = 10,
                            Cantidade = 15,
                            CategoriaId = 3,
                            Descripcion = "Canon Digital Camera - Camara dixital de alta calidade de Canon",
                            ImaxeUrl = "/Imaxes/Electronica/Electronica5.png",
                            Nome = "Canon Digital Camera",
                            Precio = 500m
                        },
                        new
                        {
                            Id = 11,
                            Cantidade = 60,
                            CategoriaId = 3,
                            Descripcion = "Gameboy - De Nintendo. A gameboy clásica da tua infancia",
                            ImaxeUrl = "/Imaxes/Electronica/electronica6.png",
                            Nome = "Nintendo Gameboy",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 12,
                            Cantidade = 212,
                            CategoriaId = 2,
                            Descripcion = "Unha silla moi comoda para mentes inquietas",
                            ImaxeUrl = "/Imaxes/Mobles/Mobles1.png",
                            Nome = "Silla de Oficina de Coiro Negro",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 13,
                            Cantidade = 112,
                            CategoriaId = 2,
                            Descripcion = "Silla de oficina con sensibilidade a flor de pel e cor de bonitas plantas",
                            ImaxeUrl = "/Imaxes/Mobles/Mobles2.png",
                            Nome = "Silla de Oficina de Coiro Rosa",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 14,
                            Cantidade = 90,
                            CategoriaId = 2,
                            Descripcion = "Unha silla moi comoda para sentarse durante horas",
                            ImaxeUrl = "/Imaxes/Mobles/Mobles3.png",
                            Nome = "Silla de Salon",
                            Precio = 70m
                        },
                        new
                        {
                            Id = 15,
                            Cantidade = 95,
                            CategoriaId = 2,
                            Descripcion = "Comodisima e destellante como o cromo, para impactar as tuas visitas",
                            ImaxeUrl = "/Imaxes/Mobles/Mobles4.png",
                            Nome = "Silla de Salon Plateada",
                            Precio = 120m
                        },
                        new
                        {
                            Id = 16,
                            Cantidade = 100,
                            CategoriaId = 2,
                            Descripcion = "Lampara de mesa de porcelana branca e azul que ni Porcelanosa a facía tan bonita",
                            ImaxeUrl = "/Imaxes/Mobles/Mobles6.png",
                            Nome = "Lampara de Mesa de Porcelana",
                            Precio = 15m
                        },
                        new
                        {
                            Id = 17,
                            Cantidade = 73,
                            CategoriaId = 2,
                            Descripcion = "Unha lampara de mesa que esta ahi, pero pasa desapercibida",
                            ImaxeUrl = "/Imaxes/Mobles/Mobles7.png",
                            Nome = "Lampara de Mesa de Oficina",
                            Precio = 20m
                        },
                        new
                        {
                            Id = 18,
                            Cantidade = 50,
                            CategoriaId = 4,
                            Descripcion = "Tenis moi comodos en diferentes tamaños",
                            ImaxeUrl = "/Imaxes/Calzado/Calzado1.png",
                            Nome = "Tenis Puma",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 19,
                            Cantidade = 60,
                            CategoriaId = 4,
                            Descripcion = "Unhas moi coloridas zapatillas deportivas disponibles en diferentes tamanhos para ti",
                            ImaxeUrl = "/Imaxes/Calzado/Calzado2.png",
                            Nome = "Deportivas coloridas",
                            Precio = 150m
                        },
                        new
                        {
                            Id = 20,
                            Cantidade = 70,
                            CategoriaId = 4,
                            Descripcion = "Tenis Blue Nike Trainers - porque ti o vales",
                            ImaxeUrl = "/Imaxes/Calzado/Calzado3.png",
                            Nome = "Tenis Blue Nike",
                            Precio = 200m
                        },
                        new
                        {
                            Id = 21,
                            Cantidade = 120,
                            CategoriaId = 4,
                            Descripcion = "Colorful Hummel Trainers - available in most sizes",
                            ImaxeUrl = "/Imaxes/Calzado/Calzado4.png",
                            Nome = "Deportivas Coloridas Hummel",
                            Precio = 120m
                        },
                        new
                        {
                            Id = 22,
                            Cantidade = 100,
                            CategoriaId = 4,
                            Descripcion = "Unhas zapatillas elegantes disponhibles en varios tamanhos",
                            ImaxeUrl = "/Imaxes/Calzado/Calzado5.png",
                            Nome = "Deportivas Nike Vermellas",
                            Precio = 200m
                        },
                        new
                        {
                            Id = 23,
                            Cantidade = 150,
                            CategoriaId = 4,
                            Descripcion = "Sandalias para xente chic",
                            ImaxeUrl = "/Imaxes/Calzado/Calzado6.png",
                            Nome = "Sandalias Birkenstock",
                            Precio = 50m
                        });
                });

            modelBuilder.Entity("TendaUltramarinos.Api.Entidades.ProductoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IconoCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductoCategorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconoCss = "fas fa-spa",
                            Nome = "Beleza"
                        },
                        new
                        {
                            Id = 2,
                            IconoCss = "fas fa-couch",
                            Nome = "Mobles"
                        },
                        new
                        {
                            Id = 3,
                            IconoCss = "fas fa-headphones",
                            Nome = "Electronica"
                        },
                        new
                        {
                            Id = 4,
                            IconoCss = "fas fa-shoe-prints",
                            Nome = "Calzado"
                        });
                });

            modelBuilder.Entity("TendaUltramarinos.Api.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeUsuario = "Laurie"
                        },
                        new
                        {
                            Id = 2,
                            NomeUsuario = "Sara"
                        });
                });

            modelBuilder.Entity("TendaUltramarinos.Api.Entidades.Producto", b =>
                {
                    b.HasOne("TendaUltramarinos.Api.Entidades.ProductoCategoria", "ProductoCategoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoCategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
